MySQL receiver updated from contrib collector
observIQ/opentelemetry-components pull request #2
Opened 2021-07-15 15:29 UTC by JonathanWamsley

Adding a feature - MySQL receiver

The MySQL receiver scraps metrics using a Global Status and Innodb Query. There are 14 metrics collected or with labels 67.

A README specifying config requirements is outlined.
Additionally, an example config.yaml file is shown in the testdata/config.yaml file.

2021-07-15 18:00 UTC, djaglowski requested changes
Overall structure is good, but a number of changes are necessary.

2021-07-15 18:00 UTC, djaglowski commented on receiver/mysqlreceiver/scraper.go
> +}
I have a todo to handle parse errors, which I'll roll back into this receiver. Generally though, we can't bury errors, since the value of `f` or `i` would always just be set to `0`, and we'd never know anything was wrong.

2021-07-16 10:10 UTC, JonathanWamsley commented on receiver/mysqlreceiver/config.go
> +	User                                    string `mapstructure:"user"`
Fixed

2021-07-16 10:12 UTC, JonathanWamsley commented on receiver/mysqlreceiver/factory_test.go
> +	require.NoError(t, err)
Will fix

2021-07-16 10:15 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client.go
> +	return result, err
Will fix

2021-07-16 10:15 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client.go
> +	return result, err
Will fix

2021-07-16 10:16 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client_test.go
> +}
will fix. There are no test files now. Renamed from client_test.go to client_mock.go

2021-07-16 10:17 UTC, JonathanWamsley commented on receiver/mysqlreceiver/README.md
> +MySQL receiver supports MySQL version 8.0.25
Will fix

2021-07-16 10:18 UTC, JonathanWamsley commented on receiver/mysqlreceiver/metadata.yaml
> +labels:
will fix

2021-07-16 10:36 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client.go
> +func Query(c mySQLClient, query string) ([]*Stat, error) {
will fix

2021-07-16 10:37 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client.go
> +	return nil
will fix

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper.go
> +	}
parameters are now validated during creation in the factory

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper.go
> +			// 	// buffer_pool_operations
will fix

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper.go
> +			// 	// buffer_pool_size
will fix

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper_test.go
> +	require.Equal(t, 14, len(metadata.M.Names()))
will fix

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/testdata/global_stats.txt
> +Rsa_public_key	-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0PGhrAm/jJELoNVd9usm\nAtefAJGI2h4VhCc2AQBVKkXrcOMes0r/EGeyQxCBcnBzblpy3yAnegpbTTJcV3EU\nc1J6wQBOkYoQKaLjy7Tc8Abn
will fix

2021-07-16 10:38 UTC, JonathanWamsley commented on receiver/mysqlreceiver/testdata/global_stats.txt
> +Caching_sha2_password_rsa_public_key	-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0PGhrAm/jJELoNVd9usm\nAtefAJGI2h4VhCc2AQBVKkXrcOMes0r/EGeyQxCBcnBzblpy3yAnegpbTTJcV3EU\nc1
will fix

2021-07-16 10:40 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper.go
> +}
changed to the version shown in the httpd version.

2021-07-16 11:02 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client.go
> +	connStr := fmt.Sprintf("%s:%s@tcp(%s)/", conf.user, conf.pass, conf.endpoint)
I tired removing env files like password and I was getting No password error. 

Error:          Expected nil, but got: &mysql.MySQLError{Number:0x415, Message:"Access denied for user ''@'172.17.0.1' (using password: NO)"}

Error:          Expected nil, but got: &mysql.MySQLError{Number:0x415, Message:"Access denied for user 'otel'@'172.17.0.1' (using password: NO)"}

2021-07-16 11:20 UTC, JonathanWamsley commented on receiver/mysqlreceiver/README.md
> +
will fix

2021-07-16 11:22 UTC, JonathanWamsley commented on receiver/mysqlreceiver/README.md
> +- `password`
I believe they are still required. I tired removing env files like password and I was getting No password error.

Error: Expected nil, but got: &mysql.MySQLError{Number:0x415, Message:"Access denied for user ''@'172.17.0.1' (using password: NO)"}

Error: Expected nil, but got: &mysql.MySQLError{Number:0x415, Message:"Access denied for user 'otel'@'172.17.0.1' (using password: NO)"}

2021-07-16 15:31 UTC, djaglowski commented on receiver/mysqlreceiver/client.go
> +	connStr := fmt.Sprintf("%s:%s@tcp(%s)/", conf.user, conf.pass, conf.endpoint)
Technically it's possible to support no-auth, but we can worry about that in a future release if necessary. Let's just require user & password for now.

2021-07-16 15:35 UTC, JonathanWamsley commented on receiver/mysqlreceiver/scraper.go
> +	if !m.client.Closed() {
will fix

2021-07-16 16:57 UTC, djaglowski commented on cmd/otelcompcol/components.go
> +>>>>>>> master
Jon, you need validate that your code builds, runs, passes tests, before pushing.

2021-07-16 16:57 UTC, djaglowski commented on receiver/mysqlreceiver/README.md
> +There are 2 queries that are used to collect metrics, `globalstatus` and `innodb_metrics`. There's a lot of overlap between them, and the `globalstatus` can collect all but the `buffer_pool_size` met
```suggestion
Collecting most metrics requires the ability to execute `SHOW GLOBAL STATUS`. The `buffer_pool_size` metric requires access to the `information_schema.innodb_metrics` table. Please refer to [setup.sh](/receiver/mysqlreceiver/testdata/scripts/setup.sh) for an example of how to configure these permissions. 
```

Cleaning this up a bit.

2021-07-16 16:57 UTC, djaglowski commented on receiver/mysqlreceiver/client_mock.go
> +}
Can remove

2021-07-16 16:57 UTC, djaglowski commented on receiver/mysqlreceiver/factory.go
> +//go:generate mdatagen metadata.yaml
Not sure this is needed. It's just informative, right?

2021-07-16 16:57 UTC, djaglowski commented on receiver/mysqlreceiver/metadata.yaml
> +  buffer_pool_pages_state:
@JonathanWamsley , unfortunately, it appears that using `state` at the label for all metrics is incorrect. This is likely just a renaming though. Here's an example. Note they are using `kind`, `type`, `operation`, `command`, etc: https://cloud.google.com/monitoring/api/metrics_agent#agent-mysql

2021-07-16 17:51 UTC, djaglowski commented on receiver/mysqlreceiver/factory.go
> +//go:generate mdatagen metadata.yaml
Nevermind, I see now that this is necessary for `make generate`

2021-07-16 17:53 UTC, djaglowski commented on receiver/mysqlreceiver/metadata.yaml
>    buffer_pool_operations_state:
Let's drop the `_state` from all of these names as well.

2021-07-16 17:57 UTC, JonathanWamsley commented on receiver/mysqlreceiver/factory.go
> +//go:generate mdatagen metadata.yaml
Just tested, and it is needed

2021-07-16 17:59 UTC, JonathanWamsley commented on receiver/mysqlreceiver/README.md
> +There are 2 queries that are used to collect metrics, `globalstatus` and `innodb_metrics`. There's a lot of overlap between them, and the `globalstatus` can collect all but the `buffer_pool_size` met
will fix

2021-07-16 18:04 UTC, JonathanWamsley commented on receiver/mysqlreceiver/metadata.yaml
> +  buffer_pool_pages_state:
updated, though all the metrics listed have a database listed as well. Value only accepts a single value though. I am not sure what to do for the innodb/doublewrite_count metric that lists both `database`: The name of the database. and 
`kind`: TODO. Just left it at kind for now.

2021-07-16 18:04 UTC, JonathanWamsley commented on cmd/otelcompcol/components.go
> +>>>>>>> master
will fix

2021-07-16 18:10 UTC, JonathanWamsley commented on receiver/mysqlreceiver/metadata.yaml
>    buffer_pool_operations_state:
will fix

2021-07-16 18:24 UTC, JonathanWamsley commented on receiver/mysqlreceiver/client_mock.go
> +}
will fix

2021-07-16 18:25 UTC, djaglowski commented on receiver/mysqlreceiver/metadata.yaml
> +  buffer_pool_pages_state:
No problem. I noticed the `database` thing as well. Let's discuss that one after the rest is addressed.

2021-07-19 18:47 UTC, JonathanWamsley commented on receiver/mysqlreceiver/metadata.yaml
> +  buffer_pool_pages_state:
fixed

2021-07-19 20:25 UTC, djaglowski commented
@JonathanWamsley Please merge master

2021-07-20 19:24 UTC, djaglowski approved these changes

2021-07-20 19:25 UTC, djaglowski commented
Nice job @JonathanWamsley!

2021-07-20 19:25 UTC, merged