Update mongo tests
observIQ/opentelemetry-components pull request #46
Opened 2021-08-18 20:06 UTC by Mrod1598

Update the scraper test and integration test to further validate we are getting the metrics correctly. had to move the client to the scraper struct so I could mock it and move the init of it into a start function.

2021-08-19 20:09 UTC, djaglowski requested changes
Nice cleanup, but introduced a problem that we need to resolve.

2021-08-19 20:09 UTC, djaglowski commented on receiver/mongodbreceiver/factory.go
> +	}
Turns out this is already called by the collector, so we don't need to call it here. (just need to have a `Validate` method on the config)

2021-08-19 20:09 UTC, djaglowski commented on receiver/mongodbreceiver/scraper.go
>  	}()
I believe you've introduced a bug here. The client is created once, but is disconnected after the first call to `scrape`.

In general, it's pretty risky to rely on a persistent client connection forever. (even if we're not telling it to disconnect) Let's re-up the client each interval, so that if something goes wrong we can just retry next time.

2021-08-20 15:42 UTC, djaglowski approved these changes

2021-08-20 15:45 UTC, Mrod1598 commented on receiver/mongodbreceiver/scraper.go
>  	}()
Updated the initClient function to just create the client then connect in the scraper so I can mock it properly still and get rid of that bug.

2021-08-20 15:45 UTC, Mrod1598 commented on receiver/mongodbreceiver/factory.go
> +	}
removed

2021-08-20 15:54 UTC, merged