Elasticsearch: use node name instead of node id
observIQ/opentelemetry-components pull request #69
Opened 2021-09-14 19:07 UTC by djaglowski

2021-09-14 21:27 UTC, JonathanWamsley approved these changes
lgtm

2021-09-14 21:28 UTC, jsirianni commented
I am building this locally and deploying to my env

2021-09-14 23:10 UTC, jsirianni requested changes
I am getting some errors, we can discuss tomorrow. It may be user error.

2021-09-23 17:27 UTC, jsirianni approved these changes

2021-09-23 20:05 UTC, merged